version: '3.8'

services:
  web:
    build: .
    image: local_marketplace
    command: -m uvicorn app.main:app --reload --host 0.0.0.0 --port 5000 --workers=1
    env_file: marketplace.env
    volumes:
      - ./app:/app/app
      - ./etc:/app/etc
      - ./tests:/app/tests
    ports:
      - 5000:5000
